In [1]:
import pandas as pd
import numpy as np

In [4]:
input_vol = np.load('input_vol.npy')
input_label = np.load('input_label.npy')
input_vol.shape

(370, 6, 300)

In [8]:
s = np.arange(input_vol.shape[0])
np.random.shuffle(s)
s

array([184,  61, 336, 205,  50, 113, 362, 194, 127, 168, 250,  45,   9,
       245, 114, 182,   5,  97, 230,  15, 209, 291, 299, 100, 124,  55,
        68, 142, 193,  52,   1, 143, 224,  11,  99, 312, 158,  23,  64,
       137,  54, 198, 223, 324,  16, 105, 183, 366, 147, 304, 270,   6,
       207, 298, 107,  14, 279, 213,  44, 222, 315, 283, 249,  30, 314,
       284, 328, 129, 119,  81, 115, 260, 333,  88, 272, 125,  27, 350,
       318, 367,  38, 218, 263, 165, 338, 196, 356, 293, 289,  95, 273,
         2,  60, 360, 135, 276, 153, 177, 351, 269, 307, 154,  17,  49,
       339, 255, 305, 164, 274, 214, 337, 321, 210, 349, 189, 163, 104,
        26, 239, 316,   3, 342, 308, 240,  86, 257, 136,  93, 208, 169,
       368, 233, 170, 248, 131, 344, 191, 220, 253, 175, 325, 231, 243,
        10,  70,  25,  62,  71, 217, 216, 134,  40, 323, 228, 354,  98,
       361, 271,  12, 331,  46, 335, 121, 171, 343, 345, 227, 192, 130,
       201,  63, 145,  53,  57,   8,  28, 295,  84, 102, 292, 27

In [12]:
input_vol[s][0][0] == input_vol[184][0]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [17]:
input_label[s][0] == input_label[184] 

array([ True,  True,  True,  True], dtype=bool)